"""Emit every number and table the paper reports, straight from the results.

The paper must contain no hand-typed figures. Transcribing them by hand failed
twice: once in the per-detector table, and once across the whole manuscript
when the adapters were corrected and the prose was not regenerated. A reviewer
holding the artifact finds that in minutes, and for a paper about silent
inconsistency it is the worst possible defect to ship.

This module writes:

    numbers.tex        \\newcommand macros for every scalar in the prose
    tab_family.tex     danger by statistic family
    tab_probes.tex     danger by probe, all 14
    tab_detectors.tex  per-detector counts

The paper \\input{}s these. Re-running the audit and this script leaves the
manuscript correct by construction.
"""

from __future__ import annotations

import argparse
import csv
from collections import Counter, defaultdict
from pathlib import Path

from driftaudit.analysis import (
    CONTROL_FAMILY,
    FIELD_FAMILY,
    TUTORIAL_FAMILY,
    bootstrap_gap,
    family,
    family_gap,
)
from driftaudit.outcomes import DANGEROUS

# Human-readable probe labels, in the paper's wording.
PROBE_LABEL = {
    "degenerate_reference": "Reference constant",
    "degenerate_current": "Current constant",
    "both_constant_equal": "Both constant, equal",
    "both_constant_different": "Both constant, different",
    "disjoint_support": "Current outside ref.\\ range",
    "empty_reference_bins": "Current fills reference gap",
    "tiny_current_n3": "Current $n{=}3$",
    "tiny_both_n5": "Both windows $n{=}5$",
    "empty_current": "Current empty",
    "all_nan_current": "Current all \\texttt{NaN}",
    "partial_nan_current": "Current half \\texttt{NaN}",
    "inf_in_current": "Current contains $\\infty$",
    "control_no_shift": "\\textbf{Control: no shift}",
    "control_large_shift": "\\textbf{Control: large shift}",
}
FAMILY_ORDER_NOTE = (CONTROL_FAMILY, FIELD_FAMILY)


#: Display names. Not derived by capitalisation, which lowercases "PSI".
FAMILY_LABEL = {
    "streaming detector": "Streaming detector",
    "p-value test": "p-value test",
    "published tutorial PSI": "Published tutorial PSI",
    "divergence / distance": "Divergence / distance",
    "field defect (n=1)": "Field defect ($n{=}1$)",
    "reference impl. (control)": "Reference impl.\ (control)",
}


def _write_tabular(path: Path, cols: str, header: str, body: list[str]) -> None:
    r"""Emit a complete tabular environment, not just its rows.

    ``\input`` of a bare row fragment *inside* a ``tabular`` breaks at the file
    boundary: TeX stops treating the fragment's final ``\\`` as a row
    terminator, so the following ``\bottomrule`` lands outside an alignment and
    raises "Misplaced \noalign". Generating the whole environment and inputting
    it at table level avoids the problem entirely.
    """
    parts = [
        "% Generated by driftaudit.paper_numbers -- do not edit.\n",
        "\\begin{tabular}{" + cols + "}\n",
        "\\toprule\n",
        header + " \\\\\n",
        "\\midrule\n",
        *body,
        "\\bottomrule\n",
        "\\end{tabular}\n",
    ]
    path.write_text("".join(parts), encoding="utf-8")


def _label(f: str) -> str:
    return FAMILY_LABEL.get(f, f)


def _pct(x: float) -> str:
    return f"{round(x * 100)}\\%"


def emit(rows: list[dict], out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    n_cells = len(rows)
    verdicts = Counter(r["verdict"] for r in rows)
    dangerous = sum(verdicts[v] for v in DANGEROUS)
    detectors = sorted({r["detector"] for r in rows})
    probes = list(dict.fromkeys(r["probe"] for r in rows))

    per_det: dict[str, int] = defaultdict(int)
    for r in rows:
        per_det[r["detector"]] += r["verdict"] in DANGEROUS
    clean = sorted(d for d in detectors if per_det[d] == 0)

    pv, dv, gap = family_gap(rows)
    lo, hi, n_pv, n_dv = bootstrap_gap(rows)
    lolo = {}
    for lib in sorted({d.split("/")[0] for d in detectors}):
        _, _, g = family_gap(rows, drop_library=lib)
        if g == g:
            lolo[lib] = g

    # ---- scalar macros ----------------------------------------------------
    m: dict[str, str] = {
        "NumDetectors": str(len(detectors)),
        "NumProbes": str(len(probes)),
        "NumCells": str(n_cells),
        "NumDangerous": str(dangerous),
        "PctDangerous": _pct(dangerous / n_cells),
        "NumFailSilent": str(verdicts["fail-silent"]),
        "NumFailMiss": str(verdicts["fail-miss"]),
        "NumFailNoisy": str(verdicts["fail-noisy"]),
        "NumFailAlarm": str(verdicts["fail-alarm"]),
        "NumSafeUndefined": str(verdicts["safe-undefined"]),
        "NumError": str(verdicts["error"]),
        "NumPass": str(verdicts["pass"]),
        "PctPValue": _pct(pv),
        "PctDivergence": _pct(dv),
        "GapPP": f"{round(gap * 100)}",
        "GapLoPP": f"{round(lo * 100)}",
        "GapHiPP": f"{round(hi * 100)}",
        "NumPValueDetectors": str(n_pv),
        "NumDivergenceDetectors": str(n_dv),
        "LoloMinPP": f"{round(min(lolo.values()) * 100)}",
        "LoloMaxPP": f"{round(max(lolo.values()) * 100)}",
        "NumClean": str(len(clean)),
        "CleanList": ", ".join(
            "\\texttt{" + c.replace("_", "\\_") + "}" for c in clean),
    }
    # control detail
    for probe in ("control_no_shift", "control_large_shift"):
        sub = [r for r in rows if r["probe"] == probe]
        key = "NoShift" if probe == "control_no_shift" else "LargeShift"
        m[f"Ctrl{key}Dangerous"] = str(sum(1 for r in sub if r["verdict"] in DANGEROUS))
        m[f"Ctrl{key}Alarm"] = str(sum(1 for r in sub if r["verdict"] == "fail-alarm"))
    # degeneracy noisy count, quoted in prose
    deg = [r for r in rows if r["probe"] == "degenerate_reference"]
    m["DegenerateNoisy"] = str(sum(1 for r in deg if r["verdict"] == "fail-noisy"))
    m["DegenerateDangerous"] = str(sum(1 for r in deg if r["verdict"] in DANGEROUS))

    # ---- family rates quoted in prose ------------------------------------
    fam_rate: dict[str, list[int]] = defaultdict(lambda: [0, 0])
    for r in rows:
        f = family(r["detector"])
        fam_rate[f][0] += r["verdict"] in DANGEROUS
        fam_rate[f][1] += 1
    for fam_key, macro in (("streaming detector", "PctStreaming"),
                           (TUTORIAL_FAMILY, "PctTutorial")):
        if fam_key in fam_rate:
            d, n = fam_rate[fam_key]
            m[macro] = _pct(d / n)

    # ---- corroboration counts quoted when defending probe expectations ---
    bcd = [r for r in rows if r["probe"] == "both_constant_different"]
    m["CorroborateShift"] = str(sum(1 for r in bcd if r["outcome"] == "silent-drift"))
    pnc = [r for r in rows if r["probe"] == "partial_nan_current"]
    n_nan = sum(1 for r in pnc if r["outcome"] == "explicit-undefined")
    n_raise = sum(1 for r in pnc if r["outcome"] == "raised")
    m["CorroborateNaN"] = str(n_nan)
    m["CorroborateRaise"] = str(n_raise)
    m["CorroborateExplicit"] = str(n_nan + n_raise)
    m["CorroborateQuiet"] = str(sum(1 for r in pnc if r["outcome"] == "silent-stable"))
    # detectors that return NaN/None somewhere -- cited as "the machinery exists"
    m["NanReturners"] = str(len({r["detector"] for r in rows
                                 if r["outcome"] == "explicit-undefined"}))

    # ---- per-probe rates quoted in prose ---------------------------------
    probe_rate: dict[str, list[int]] = defaultdict(lambda: [0, 0])
    for r in rows:
        probe_rate[r["probe"]][0] += r["verdict"] in DANGEROUS
        probe_rate[r["probe"]][1] += 1
    for probe, macro in (("tiny_both_n5", "RateTinyBoth"),
                         ("tiny_current_n3", "RateTinyCurrent"),
                         ("inf_in_current", "RateInf"),
                         ("degenerate_reference", "RateDegenerate")):
        d, n = probe_rate[probe]
        m[macro] = _pct(d / n)

    # ---- why a gate could not answer: a three-way split ------------------
    # Kept explicit because "most dangerous cells are underpowered" was
    # asserted without checking and is false: no class holds a majority.
    UNDEFINED_PROBES = {"degenerate_reference", "empty_current", "all_nan_current",
                        "inf_in_current", "partial_nan_current"}
    UNDERPOWERED_PROBES = {"tiny_current_n3", "tiny_both_n5"}
    split = Counter()
    for r in rows:
        if r["verdict"] not in DANGEROUS:
            continue
        if r["probe"] in UNDERPOWERED_PROBES:
            split["underpowered"] += 1
        elif r["probe"] in UNDEFINED_PROBES:
            split["undefined"] += 1
        else:
            split["missed"] += 1
    for key, macro in (("undefined", "DangUndefined"),
                       ("underpowered", "DangUnderpowered"),
                       ("missed", "DangMissed")):
        m[macro] = str(split[key])
        m[macro + "Pct"] = _pct(split[key] / dangerous)

    # ---- static sweep joined against behaviour ---------------------------
    sweep = Path("results/corpus_sweep.csv")
    if not sweep.exists():
        sweep = out.parents[1] / "results/corpus_sweep.csv"
    if sweep.exists():
        static = {r["detector"]: r["verdict"]
                  for r in csv.DictReader(sweep.open(encoding="utf-8"))}
        joint: dict[str, list[int]] = defaultdict(lambda: [0, 0, 0])
        for det, bad in per_det.items():
            v = static.get(det, "unresolved")
            joint[v][0] += bad
            joint[v][1] += sum(1 for r in rows if r["detector"] == det)
            joint[v][2] += 1
        for key, macro in (("explicit", "Guard"), ("no-guard", "NoGuard"),
                           ("smoothing", "Smoothing"), ("silent-zero", "SilentZero")):
            if key in joint:
                b, n, k = joint[key]
                m[f"{macro}Dang"] = str(b)
                m[f"{macro}Cells"] = str(n)
                m[f"{macro}Pct"] = _pct(b / n)
                m[f"{macro}Impls"] = str(k)
        lines = []
        for v, (b, n, k) in sorted(joint.items(), key=lambda x: -x[1][0] / max(x[1][1], 1)):
            lines.append(f"{v} & {k} & {b}/{n} ({_pct(b / n)}) \\\\\n")
        _write_tabular(out / "tab_corpus.tex", "@{}lrr@{}",
                       r"\textbf{Static class} & \textbf{Impls.} & \textbf{Behavioural danger}",
                       lines)

    (out / "numbers.tex").write_text(
        "% Generated by driftaudit.paper_numbers -- do not edit.\n"
        + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in sorted(m.items())),
        encoding="utf-8",
    )

    # ---- family table -----------------------------------------------------
    fam: dict[str, list[int]] = defaultdict(lambda: [0, 0])
    for r in rows:
        f = family(r["detector"])
        fam[f][0] += r["verdict"] in DANGEROUS
        fam[f][1] += 1
    subjects = [(f, v) for f, v in fam.items() if f not in FAMILY_ORDER_NOTE]
    others = [(f, v) for f, v in fam.items() if f in FAMILY_ORDER_NOTE]
    lines = []
    for f, (d, n) in sorted(subjects, key=lambda x: -x[1][0] / x[1][1]):
        label = _label(f) + ("$^{\\dagger}$" if f == "streaming detector" else "")
        best = "\\textbf{" + _pct(d / n) + "}" if f == "divergence / distance" else _pct(d / n)
        lines.append(f"{label} & {d}/{n} & {best} \\\\\n")
    lines.append("\\midrule\n")
    for f, (d, n) in sorted(others, key=lambda x: -x[1][0] / max(x[1][1], 1)):
        lines.append(f"{_label(f)} & {d}/{n} & {_pct(d / n)} \\\\\n")
    _write_tabular(out / "tab_family.tex", "@{}lrr@{}",
                   r"\textbf{Statistic family} & \textbf{Dangerous} & \textbf{Rate}",
                   lines)

    # ---- probe table ------------------------------------------------------
    pa: dict[str, list[int]] = defaultdict(lambda: [0, 0, 0, 0])
    for r in rows:
        a = pa[r["probe"]]
        a[0] += r["verdict"] in DANGEROUS
        a[1] += 1
        a[2] += r["verdict"] == "fail-noisy"
        a[3] += r["verdict"] == "fail-alarm"
    lines = []
    for p, (d, n, noisy, alarm) in sorted(pa.items(), key=lambda x: -x[1][0] / x[1][1]):
        label = PROBE_LABEL.get(p, p)
        dcell = f"\\textbf{{{d}}}" if p.startswith("control") else str(d)
        acell = f"\\textbf{{{alarm}}}" if alarm and p.startswith("control") else str(alarm)
        lines.append(f"{label} & {dcell} & {_pct(d / n)} & {noisy} & {acell} \\\\\n")
    _write_tabular(out / "tab_probes.tex", "@{}lrrrr@{}",
                   r"\textbf{Probe} & \textbf{\textsc{d}} & \textbf{Rate} & "
                   r"\textbf{\textsc{n}} & \textbf{\textsc{a}}",
                   lines)

    # ---- per-detector table ----------------------------------------------
    ordered = sorted(per_det.items(), key=lambda x: (x[1], x[0]))
    half = (len(ordered) + 1) // 2
    left, right = ordered[:half], ordered[half:]
    lines = []
    for i in range(half):
        a = f"\\texttt{{{left[i][0]}}} & {left[i][1]}"
        b = (f"\\texttt{{{right[i][0]}}} & {right[i][1]}"
             if i < len(right) else " & ")
        lines.append(f"{a} & {b} \\\\\n".replace("_", "\\_"))
    _write_tabular(out / "tab_detectors.tex",
                   r"@{}lr@{\hspace{1.2em}}lr@{}",
                   r"\textbf{Detector} & \textbf{D} & \textbf{Detector} & \textbf{D}",
                   lines)

    # ---- sensitivity to the two contested probe expectations -------------
    from driftaudit.sensitivity import CONTESTED, reverdict

    base = {r["probe"]: r["expectation"] for r in rows}
    keys = list(CONTESTED)
    slines = []
    for choice in __import__("itertools").product(*(CONTESTED[k] for k in keys)):
        exp = dict(base) | dict(zip(keys, choice, strict=True))
        tally: dict[str, list[int]] = defaultdict(lambda: [0, 0])
        total = [0, 0]
        for r in rows:
            bad = reverdict(r["outcome"], exp[r["probe"]]) in DANGEROUS
            f = family(r["detector"])
            tally[f][0] += bad
            tally[f][1] += 1
            total[0] += bad
            total[1] += 1
        pvx, dvx = tally["p-value test"], tally["divergence / distance"]
        slines.append(
            f"{choice[0]} & {choice[1]} & {_pct(total[0] / total[1])} & "
            f"{_pct(pvx[0] / pvx[1])} & {_pct(dvx[0] / dvx[1])} \\\\\n")
    _write_tabular(out / "tab_sensitivity.tex", "@{}llrrr@{}",
                   r"\textbf{Both const.\ diff.} & \textbf{Half \texttt{NaN}} & "
                   r"\textbf{Overall} & \textbf{p-value} & \textbf{Divergence}",
                   slines)

    print(f"wrote numbers.tex and 5 table fragments to {out}")
    print(f"  {dangerous}/{n_cells} dangerous, p-value {pv:.0%} vs divergence {dv:.0%}")
    print(f"  clean detectors ({len(clean)}): {', '.join(clean)}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default="results/audit_matrix.csv")
    ap.add_argument("--out-dir", default="paper/generated")
    args = ap.parse_args()
    rows = list(csv.DictReader(Path(args.csv).open(encoding="utf-8")))
    emit(rows, Path(args.out_dir))


if __name__ == "__main__":
    main()
